[package]
name = "battlesnake"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
description.workspace = true
keywords.workspace = true

[dependencies]
axum = "0.7.3"
anyhow = "1.0.80"
game = { path = "../../crates/game"}
search = { path = "../../crates/search" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
shuttle-axum = "0.39.0"
shuttle-runtime = "0.39.0"
tokio = "1.28.2"
tracing = "0.1.40"
